/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DocumentationRouteImport } from './routes/documentation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomIdRouteImport } from './routes/room.$id'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRoute = DocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIdRoute = RoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/history': typeof HistoryRoute
  '/room/$id': typeof RoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/history': typeof HistoryRoute
  '/room/$id': typeof RoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documentation': typeof DocumentationRoute
  '/history': typeof HistoryRoute
  '/room/$id': typeof RoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/documentation' | '/history' | '/room/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/documentation' | '/history' | '/room/$id'
  id: '__root__' | '/' | '/documentation' | '/history' | '/room/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentationRoute: typeof DocumentationRoute
  HistoryRoute: typeof HistoryRoute
  RoomIdRoute: typeof RoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation': {
      id: '/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof DocumentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$id': {
      id: '/room/$id'
      path: '/room/$id'
      fullPath: '/room/$id'
      preLoaderRoute: typeof RoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentationRoute: DocumentationRoute,
  HistoryRoute: HistoryRoute,
  RoomIdRoute: RoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
